language: python

python:
  - 2.7

env:
  - DJANGO=Django==1.4.22
  - DJANGO=Django==1.5.12
  - DJANGO=Django==1.6.11
  - DJANGO=Django==1.7.9
  - DJANGO=Django==1.8.4

matrix:
  exclude:
    - python: 3.2
      env: DJANGO=Django==1.4.15
    - python: 3.3
      env: DJANGO=Django==1.4.15
    - python: 2.6
      env: DJANGO=Django==1.7

install:
  - pip install -q $DJANGO
  - python setup.py -q install

before_script:
  - rm -rf build

script:
  - coverage run manage.py test -v 2 dnsmanager

after_success:
  - coveralls --verbose
