language: python

python:
  - 2.7

env:
  - DJANGO=Django==1.8.17
  - DJANGO=Django==1.9.12

install:
  - pip install -q $DJANGO
  - pip install coveralls model-mommy==1.2.6
  - python setup.py -q install

before_script:
  - rm -rf build

script:
  - coverage run manage.py test -v 2 dnsmanager

after_success:
  - coveralls --verbose

sudo: false