language: python

python:
  - 2.7

env:
  - DJANGO=Django==1.7.10
  - DJANGO=Django==1.8.5

install:
  - pip install -q $DJANGO
  - pip install coveralls model_mommy
  - python setup.py -q install

before_script:
  - rm -rf build

script:
  - coverage run manage.py test -v 2 dnsmanager

after_success:
  - coveralls --verbose

sudo: false